# Generated by Django 3.2.16 on 2022-10-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='klient',
            new_name='author',
        ),
    ]
